FROM alpine:latest

# Install necessary packages
RUN apk update && apk add --no-cache git jq tar openssh-client bash

# Copy the backup script to the container
COPY backup.sh /backup.sh
RUN chmod +x /backup.sh

# Run the script 3 times
CMD ["/bin/bash", "-c", "/backup.sh"]

