version: '3.8'

services:
  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER} 
      - POSTGRES_PASSWORD=${DB_PASSWORD}  
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    ports:
      - "5432:5432"

  frontend:
    image: 347872487225.dkr.ecr.us-east-1.amazonaws.com/frontend:{{TAG}}
    ports:
      - "4200:4200"

  backend:
    image: 347872487225.dkr.ecr.us-east-1.amazonaws.com/backend:{{TAG}}
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: 347872487225.dkr.ecr.us-east-1.amazonaws.com/nginx:{{TAG}}
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
