repos:
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: ["--config=app/pyproject.toml"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--settings-path=app/pyproject.toml"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [pyproject-flake8]
        args: ["--config=app/pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        args: ['--config-file', 'app/pyproject.toml', '--show-traceback']
        name: mypy
        additional_dependencies:
          - "pydantic==2.3.0"