[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
[tool.flake8]

max-line-length = 79
exclude = ["venv"]
extend-ignore = "E203"
per-file-ignores = "__init__.py:F401"

[tool.mypy]
exclude = ["venv", "alembic"]
plugins = ["pydantic.mypy"]

strict_optional = true
check_untyped_defs = true
warn_redundant_casts = true
disallow_untyped_calls = true
disallow_untyped_defs = true
warn_incomplete_stub = true
ignore_missing_imports = true