name: Backup repo on any push or PR, track versions
run-name: Backup-${{ github.sha }}
on:
  push:
    branches:
      - main
    paths:
      - '**'
  pull_request:
    paths:
      - '**'
  workflow_dispatch: 
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      chosen-os:
        required: true
        type: choice
        options:
        - ubuntu-latest
        - ubuntu-20.04
        - self-hosted

jobs:
  backup:
    runs-on: "${{ inputs.chosen-os || 'ubuntu-latest' }}"

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p $HOME/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        ssh-keyscan github.com >> $HOME/.ssh/known_hosts     

    - name: Create necessary directories
      run: |
        sudo mkdir -p /backups
        sudo chown -R $USER:$USER /backups

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq git

    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Download versions.json from S3 if exists
      run: |
        aws s3 cp s3://devops-intern-serhieiev/versions.json /backups/versions.json || echo "versions.json does not exist yet."

    - name: Run backup.sh
      id: backup_script
      run: |
        if [ ! -f /backups/versions.json ]; then
          echo "[]" > /backups/versions.json
        fi
        bash backup.sh

    - name: Upload backup to S3
      run: |
        aws s3 cp /backups/devops_internship_${{ steps.backup_script.outputs.backup_version }}.tar.gz s3://devops-intern-serhieiev/

    - name: Upload new versions.json to S3
      run: |
        aws s3 cp /backups/versions.json s3://devops-intern-serhieiev/