name: Backend - lint, test, dockerize python BE

on:
  push:
    paths:
      - 'app/**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'app/**'
    branches:
      - '**'
  workflow_dispatch: 
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true


jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/

    strategy:
      matrix:
        python-version: [3.11]

    

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 app/

    - name: Test with pytest
      run: |
        pytest tests/

    - name: Build Docker image
      run: |
        docker build -t be_devops:latest ./app

    - name: Save Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: be_devops:latest
        path: images
        retention-days: 1