name: Frontend - lint, test, dockerize angular FE

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'frontend/**'
    branches:
      - '**'
  workflow_dispatch: 
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Chromium
      run: sudo apt-get install -y chromium-browser

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install NPM dependencies
      run: |
        cd frontend
        npm ci

    - name: Lint with npm
      run: |
        cd frontend
        npm run lint

    - name: Test with npm
      run: |
        cd frontend
        npm run test:ci

    - name: Build Docker image
      run: |
        docker build -t fe_devops:latest ./frontend

    - name: Save Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: fe_devops:latest
        path: images
        retention-days: 1
