name: Nginx - dockerize web-server

on:
  push:
    paths:
      - 'nginx/**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'nginx/**'
    branches:
      - '**'
  workflow_dispatch: 
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      chosen-os:
        required: true
        type: choice
        options:
        - ubuntu-latest
        - ubuntu-20.04
        - self-hosted

jobs:
  build:
    runs-on: "${{ inputs.chosen-os || 'ubuntu-latest' }}"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t nginx_devops:latest ./nginx

    - name: Save Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: nginx_devops:latest
        path: images
        retention-days: 1
